FROM php:7.2-fpm
RUN apt-get update && apt-get install -y \
	libpq-dev \
    libxml2-dev \
    zlib1g-dev \
    && apt-get clean -y
RUN	docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
	&& docker-php-ext-install \
    opcache \
    pdo \
    pdo_pgsql \
    pgsql \
    dom \
    mbstring \
    session \
    tokenizer \
    zip \
